# Generated by Django 5.0.4 on 2024-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
                ('prioridad', models.IntegerField(max_length=10)),
                ('fecha_realizar', models.DateTimeField(verbose_name='fecha a realizar')),
                ('estado', models.CharField(max_length=200)),
            ],
        ),
    ]
