# Generated by Django 5.0.5 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_category_remove_user_contraseña_remove_user_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
